### PR TITLE
Fix style parser font behaviour

### PR DESCRIPTION
**Pull request by edkennard**
- In several places the default font was incorrectly named "Helvetia" instead of "Helvetica"
- The way the font name was being read by the StyleParser meant a blank "font=" wasn't handled correctly. The related tests have been improved accordingly

### CODE REVIEW

**Comment by RalphSteinhagen** [comment]
@edkennard thanks for this PR! :+1:

Yes, the intended use was 'Helvetica'... the other one is cursive...

**Review by RalphSteinhagen — APPROVED** [review]
Thanks! LGTM :+1:

**Comment by edkennard** [comment]
@RalphSteinhagen Thanks for getting this merged - when will the next version be published to Maven Central?

**Comment by RalphSteinhagen** [comment]
@edkennard we plan to make a micro-release this, latest next week. 

After that we will start with a new minor version since we have quite a few internal improvements pending (changes to the event handling structure -> moving to using the Disruptor, ...). This will also come with a GH organisation and authority change from `de.gsi' -> 'io.fair-acc'. This will help simplify our deployment process internal to GSI/FAIR.

Most of the rest will stay the same though. Enjoy!

P.S. If you like, maybe you could share your use-case in the discussion ... we always love feedback on how our little lib is being used.

**Comment by edkennard** [comment]
@RalphSteinhagen ok great, thanks, the pending release will also include the PR which allows toggling of datasets, which we like.

I would be happy to add our use-case to the discussions area, will do that at a suitable moment in the next couple of weeks, once my current chart-related work is completed and merged into our product. My hope is to contribute further to the project too, as soon as time permits.

Cheers, Ed

**Pull request merged**
