### PR TITLE
refactor ioserialiser microservice

### PR DESCRIPTION
**Pull request by RalphSteinhagen**

### CODE REVIEW

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- chartfx-chart/src/main/java/de/gsi/chart/ui/ProfilerInfoBox.java  -1
- chartfx-dataset/src/main/java/de/gsi/dataset/utils/DoubleArrayCache.java  -4
- chartfx-dataset/src/main/java/de/gsi/dataset/spi/DefaultErrorDataSet.java  -25
- chartfx-dataset/src/main/java/de/gsi/dataset/utils/CacheCollection.java  -3
- chartfx-dataset/src/main/java/de/gsi/dataset/spi/DefaultAxisDescription.java  -1
- chartfx-chart/src/main/java/de/gsi/chart/ui/HiddenSidesPaneSkin.java  -1
- chartfx-dataset/src/main/java/de/gsi/dataset/testdata/spi/TriangleFunction.java  -19
- chartfx-dataset/src/main/java/de/gsi/dataset/spi/DataSetBuilder.java  -2
- chartfx-dataset/src/main/java/de/gsi/dataset/spi/AbstractDataSet.java  -6
         

Complexity increasing per file
==============================
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldListAxisDescription.java  5
- microservice/src/main/java/de/gsi/serializer/IoClassSerialiser.java  20
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitiveValueHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMultiArrayHelper.java  30
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  15
- microservice/src/main/java/de/gsi/serializer/utils/ClassUtils.java  9
- microservice/src/main/java/de/gsi/serializer/DataType.java  5
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueArrayHelper.java  1
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  3
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserBenchmark.java  3
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  13
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  21
- microservice/src/main/java/de/gsi/serializer/spi/ProtocolInfo.java  2
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  10
- microservice/src/main/java/de/gsi/serializer/spi/FastByteBuffer.java  9
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  11
- microservice/src/test/java/de/gsi/serializer/benchmark/ReflectionBenchmark.java  6
- microservice/src/test/java/de/gsi/serializer/spi/helper/MyGenericClass.java  44
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitveValueArrayHelper.java  1
- microservice/src/test/java/de/gsi/serializer/spi/IoBufferTests.java  1
- microservice/src/main/java/de/gsi/serializer/FieldSerialiser.java  8
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/test/java/de/gsi/serializer/benchmark/JsonSelectionBenchmark.java  3
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMapHelper.java  1
- microservice/src/test/java/de/gsi/serializer/IoSerialiserTests.java  7
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserSimpleTest.java  1
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserTests.java  4
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldDataSetHelper.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  8
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldCollectionsHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueHelper.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/DataSetSerialiserBenchmark.java  1
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  1
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  31
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiser.java  13
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserAssumptionsBenchmark.java  2
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  7
- microservice/src/main/java/de/gsi/serializer/spi/ByteBuffer.java  9
         

Clones added
============
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  6
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  15
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  25
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  7
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  8
- microservice/src/test/java/de/gsi/serializer/helper/SerialiserHelper.java  10
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  1
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  2
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6144395&bid=20084396)

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserTests.java  4
- microservice/src/main/java/de/gsi/serializer/spi/ProtocolInfo.java  2
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitveValueArrayHelper.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/DataSetSerialiserBenchmark.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserAssumptionsBenchmark.java  2
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  13
- microservice/src/main/java/de/gsi/serializer/spi/FastByteBuffer.java  9
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  21
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMultiArrayHelper.java  30
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  15
- microservice/src/main/java/de/gsi/serializer/IoClassSerialiser.java  20
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueHelper.java  1
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  1
- microservice/src/test/java/de/gsi/serializer/spi/helper/MyGenericClass.java  44
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMapHelper.java  1
- microservice/src/main/java/de/gsi/serializer/utils/ClassUtils.java  9
- microservice/src/main/java/de/gsi/serializer/FieldSerialiser.java  8
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldCollectionsHelper.java  1
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserSimpleTest.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/JsonSelectionBenchmark.java  3
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  7
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/test/java/de/gsi/serializer/IoSerialiserTests.java  7
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  31
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldDataSetHelper.java  1
- microservice/src/test/java/de/gsi/serializer/spi/IoBufferTests.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserBenchmark.java  3
- microservice/src/main/java/de/gsi/serializer/spi/ByteBuffer.java  9
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueArrayHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldListAxisDescription.java  5
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiser.java  13
- microservice/src/main/java/de/gsi/serializer/DataType.java  5
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  8
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  11
- microservice/src/test/java/de/gsi/serializer/benchmark/ReflectionBenchmark.java  6
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitiveValueHelper.java  1
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  3
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  10
         

Clones added
============
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  15
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  25
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  2
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  5
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/helper/SerialiserHelper.java  10
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  1
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  8
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  6
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6144395&bid=20084396)

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- microservice/src/test/java/de/gsi/serializer/benchmark/DataSetSerialiserBenchmark.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldListAxisDescription.java  5
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitveValueArrayHelper.java  1
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserTests.java  4
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMapHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/FastByteBuffer.java  9
- microservice/src/main/java/de/gsi/serializer/utils/ClassUtils.java  9
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldDataSetHelper.java  1
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserSimpleTest.java  1
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  11
- microservice/src/main/java/de/gsi/serializer/IoClassSerialiser.java  20
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiser.java  13
- microservice/src/test/java/de/gsi/serializer/benchmark/ReflectionBenchmark.java  6
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldCollectionsHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/ProtocolInfo.java  2
- microservice/src/main/java/de/gsi/serializer/spi/ByteBuffer.java  9
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitiveValueHelper.java  1
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  1
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  10
- microservice/src/test/java/de/gsi/serializer/IoSerialiserTests.java  7
- microservice/src/test/java/de/gsi/serializer/spi/helper/MyGenericClass.java  44
- microservice/src/test/java/de/gsi/serializer/spi/IoBufferTests.java  1
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  3
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  8
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMultiArrayHelper.java  30
- microservice/src/main/java/de/gsi/serializer/FieldSerialiser.java  8
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueArrayHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  13
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  7
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  15
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  31
- microservice/src/test/java/de/gsi/serializer/benchmark/JsonSelectionBenchmark.java  3
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserBenchmark.java  3
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserAssumptionsBenchmark.java  2
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  21
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueHelper.java  1
- microservice/src/main/java/de/gsi/serializer/DataType.java  5
         

Clones added
============
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  8
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  2
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  7
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  6
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  1
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  15
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  5
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  1
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  1
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  25
- microservice/src/test/java/de/gsi/serializer/helper/SerialiserHelper.java  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6144395&bid=20084396)

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- microservice/src/test/java/de/gsi/serializer/benchmark/ReflectionBenchmark.java  6
- microservice/src/test/java/de/gsi/serializer/benchmark/DataSetSerialiserBenchmark.java  1
- microservice/src/test/java/de/gsi/serializer/spi/IoBufferTests.java  1
- microservice/src/main/java/de/gsi/serializer/utils/ClassUtils.java  9
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMultiArrayHelper.java  30
- microservice/src/main/java/de/gsi/serializer/spi/ByteBuffer.java  9
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  11
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  3
- microservice/src/main/java/de/gsi/serializer/DataType.java  5
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiser.java  13
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  21
- microservice/src/test/java/de/gsi/serializer/benchmark/JsonSelectionBenchmark.java  3
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserTests.java  4
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserSimpleTest.java  1
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/main/java/de/gsi/serializer/FieldSerialiser.java  8
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserBenchmark.java  3
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  8
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserAssumptionsBenchmark.java  2
- microservice/src/main/java/de/gsi/serializer/spi/ProtocolInfo.java  2
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldListAxisDescription.java  5
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  15
- microservice/src/test/java/de/gsi/serializer/IoSerialiserTests.java  7
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldDataSetHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitiveValueHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueArrayHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  13
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMapHelper.java  1
- microservice/src/test/java/de/gsi/serializer/spi/helper/MyGenericClass.java  44
- microservice/src/main/java/de/gsi/serializer/IoClassSerialiser.java  20
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldCollectionsHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  31
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitveValueArrayHelper.java  1
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  7
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  10
- microservice/src/main/java/de/gsi/serializer/spi/FastByteBuffer.java  9
         

Clones added
============
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  8
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  6
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  25
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  1
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/helper/SerialiserHelper.java  10
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  15
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  2
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  5
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6144395&bid=20084396)

**Review by wirew0rm — APPROVED** [review]
Looks good :+1:

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldCollectionsHelper.java  1
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/DataSetSerialiserBenchmark.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitveValueArrayHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  21
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldPrimitiveValueHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMultiArrayHelper.java  30
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldDataSetHelper.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldMapHelper.java  1
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserSimpleTest.java  1
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldListAxisDescription.java  5
- microservice/src/test/java/de/gsi/serializer/benchmark/JsonSelectionBenchmark.java  3
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueArrayHelper.java  1
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  7
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiser.java  13
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  31
- microservice/src/main/java/de/gsi/serializer/FieldSerialiser.java  8
- microservice/src/test/java/de/gsi/serializer/spi/helper/MyGenericClass.java  44
- microservice/src/test/java/de/gsi/serializer/spi/IoBufferTests.java  1
- microservice/src/main/java/de/gsi/serializer/IoClassSerialiser.java  20
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  11
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  10
- microservice/src/main/java/de/gsi/serializer/DataType.java  5
- microservice/src/main/java/de/gsi/serializer/utils/ClassUtils.java  9
- microservice/src/main/java/de/gsi/serializer/spi/ByteBuffer.java  9
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  15
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  3
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserBenchmark.java  3
- microservice/src/main/java/de/gsi/serializer/spi/iobuffer/FieldBoxedValueHelper.java  1
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserAssumptionsBenchmark.java  2
- microservice/src/main/java/de/gsi/serializer/spi/FastByteBuffer.java  9
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  13
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  8
- microservice/src/main/java/de/gsi/serializer/spi/ProtocolInfo.java  2
- microservice/src/test/java/de/gsi/serializer/benchmark/ReflectionBenchmark.java  6
- microservice/src/test/java/de/gsi/serializer/IoSerialiserTests.java  7
- microservice/src/test/java/de/gsi/serializer/IoClassSerialiserTests.java  4
         

Clones added
============
- microservice/src/test/java/de/gsi/serializer/annotations/SerialiserAnnotationTests.java  2
- microservice/src/main/java/de/gsi/serializer/spi/BinarySerialiser.java  25
- microservice/src/test/java/de/gsi/serializer/helper/SerialiserHelper.java  10
- microservice/src/test/java/de/gsi/serializer/helper/JsonHelper.java  5
- microservice/src/main/java/de/gsi/serializer/spi/WireDataFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/spi/iobuffer/DataSetSerialiserTests.java  8
- microservice/src/main/java/de/gsi/serializer/spi/JsonSerialiser.java  7
- microservice/src/main/java/de/gsi/serializer/spi/ClassFieldDescription.java  1
- microservice/src/test/java/de/gsi/serializer/spi/BinarySerialiserTests.java  6
- microservice/src/test/java/de/gsi/serializer/helper/CmwLightHelper.java  9
- microservice/src/main/java/de/gsi/serializer/spi/CmwLightSerialiser.java  15
- microservice/src/test/java/de/gsi/serializer/benchmark/SerialiserQuickBenchmark.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6144395&bid=20084396)

**Review by wirew0rm — APPROVED** [review]
:+1:

**Pull request merged**
