### PR TITLE
license fixes and reduce LOGGER verbosity

### PR DESCRIPTION
**Pull request by RalphSteinhagen**

### CODE REVIEW

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ chartfx-dataset/src/test/java/de/gsi/dataset/event/EventSourceTests.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6149708&bid=20097224)

**Review by wirew0rm — APPROVED** [review]
:+1:

**Review by wirew0rm — DISMISSED** [review]
:+1:

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ chartfx-dataset/src/test/java/de/gsi/dataset/event/EventSourceTests.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6149708&bid=20097224)

**Comment by RalphSteinhagen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ chartfx-dataset/src/test/java/de/gsi/dataset/event/EventSourceTests.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GSI/chart-fx/pullRequest?prid=6149708&bid=20097224)

**Review by wirew0rm — APPROVED** [review]
:+1:

**Pull request merged**
