### PR TITLE
Chart-fx 11.2.0 development branch

### PR DESCRIPTION
**Pull request by wirew0rm**
Features/Changes
- Automatic module name: allows to use chartfx as a jpms/jigsaw module
- switch from GlyphFont and batiksvg to Ikonly with custom fonts
- simplified CSS styled properties
- Serialiser
    - move from chartfx-dataset to separate subpackage
    - add json and cmw support
    - Benchmarks to compare against different other serialisers
    - allow in-place deserialisation
- Add new GridDataSet interface for data on Cartesian grids
- MultiArrayDouble/Float/... primitive class for striding multidimensional arrays
- Add code generation to reduce need for multiple implementations for primitive types
- Make chart indicators editable and removable
- ProfilerInfoBox: control to show javafx/cpu performance and version indicators

### CODE REVIEW

**Review by RalphSteinhagen — APPROVED** [review]
lgtm. Was a good CI/CD improvement iteration... :-)

**Comment by nkoding** [comment]
> Features/Changes
> 
> * Automatic module name: allows to use chartfx as a jpms/jigsaw module
> * switch from GlyphFont and batiksvg to Ikonly with custom fonts
> * simplified CSS styled properties
> * Serialiser
>   
>   * move from chartfx-dataset to separate subpackage
>   * add json and cmw support
>   * Benchmarks to compare against different other serialisers
>   * allow in-place deserialisation
> * Add new GridDataSet interface for data on Cartesian grids
> * MultiArrayDouble/Float/... primitive class for striding multidimensional arrays
> * Add code generation to reduce need for multiple implementations for primitive types
> * Make chart indicators editable and removable
> * ProfilerInfoBox: control to show javafx/cpu performance and version indicators

Hi Ralph,

first of all: great job with this library!

My issue: 
I checked out the current master and wanted to start FinancialCandlestickSample.java.
But all I got was an error:

```
java: cannot find symbol
  symbol:   class MultiArrayDouble
  location: package de.gsi.dataset.spi.utils
```

Turns out that the class de.gsi.dataset.spi.utils.MultiArrayDouble  is not in master.

Thanks in advance for fixing this :)

**Comment by wirew0rm** [comment]
Hey @nkoding,

(I'm assuming that you are using intellij, since we have observed this problem there. If not it might still be a similar problem, so this might help nevertheless)
This is an auto generated class and intellij has some troubles with running the code generation maven plugin because it is located in a submodule of the project where intellij's maven emulation does not look for plugins. If you compile on the command line with mvn compile, everything should be fine and subsequent builds in intellij should also work.
If you want to be able to perform clean builds from intellij, you have to do a `mvn install` from the command line once, subsequent builds will then use the code generation plugin from your local maven repository.

This should do the trick, sorry for the inconvenience. If it does not, please open a separate issue, i was a little bit confused by this old pull request popping up out of nowhere ;-) (You can still link to it #255 if you think that it is related.)

**Comment by nkoding** [comment]
> Hey @nkoding,
> 
> (I'm assuming that you are using intellij, since we have observed this problem there. If not it might still be a similar problem, so this might help nevertheless)
> This is an auto generated class and intellij has some troubles with running the code generation maven plugin because it is located in a submodule of the project where intellij's maven emulation does not look for plugins. If you compile on the command line with mvn compile, everything should be fine and subsequent builds in intellij should also work.
> If you want to be able to perform clean builds from intellij, you have to do a `mvn install` from the command line once, subsequent builds will then use the code generation plugin from your local maven repository.
> 
> This should do the trick, sorry for the inconvenience. If it does not, please open a separate issue, i was a little bit confused by this old pull request popping up out of nowhere ;-) (You can still link to it #255 if you think that it is related.)

Hi wirew0rm thanks for the quick reply :)
I will open an issue since this didn't help.

**Pull request merged**
